version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - API_BASE_URL=/api/orders
    ports:
      - "3309:3309"
    environment:
      - DB_HOST=${DB_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - API_BASE_URL=${API_BASE_URL}
      - PORT=${PORT}
