# .github/workflows/ci.yml
name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Or your desired Node.js version

      - name: Install backend dependencies
        run: cd backend && npm install && cd ..

      - name: Install frontend dependencies
        run: cd frontend && npm install && cd ..

      - name: Run backend tests
        run: npm test --prefix backend

      - name: Run frontend tests
        run: npm test --prefix frontend

      - name: Build Docker images
        run: docker compose build